# Example 1

In [12]:
from scipy.stats import chi2_contingency, chi2
import numpy as np

observed = np.array([[10, 50, 35],[15, 60, 40]])
chi2_, p, dof, expected = chi2_contingency(observed)
critical_value = chi2.ppf(0.95, dof)
if(critical_value<chi2_):
    print (f"Reject :critical: {critical_value}\tcalculated: {chi2_}")
else:    
    print (f"Fail to Reject :critical: {critical_value}\tcalculated: {chi2_}")



Fail to Reject :critical: 5.991464547107979	calculated: 0.3407530684418557


In [ ]:
from scipy.stats import  chi2
import numpy as np

row_total = np.array([95, 115])
column_total = np.array([25, 110, 75])
total = 210


observed = np.array([[10, 50, 35],[15, 60, 40]])
expected = np.array([[0.0,0.0,0.0],[0.0,0.0,0.0]])

for i in range(0, len(row_total)):
    for j in range(0, len(column_total)):
        expected[i][j] = row_total[i]*column_total[j]/total

_chi = 0

for i in range(0, 2):
    for j in range(0, 3):
        _chi = _chi + ((observed[i][j]-expected[i][j]) ** 2)/expected[i][j]

print(expected)
if(critical_value<_chi):
    print (f"Reject :critical: {critical_value}\tcalculated: {_chi}")
else:    
    print (f"Fail to Reject :critical: {critical_value}\tcalculated: {_chi}")



11.30952380952381 - 10
49.76190476190476 - 50
33.92857142857143 - 35
13.69047619047619 - 15
60.23809523809524 - 60
41.07142857142857 - 40
[[11.30952381 49.76190476 33.92857143]
 [13.69047619 60.23809524 41.07142857]]
Fail to Reject :critical: 3.841458820694124	calculated: 0.3407530684418557


# Example 2

In [59]:
from scipy.stats import  chi2
import numpy as np

row_total = np.array([120, 180])
column_total = np.array([36, 264])
total = 300


observed = np.array([[12, 108],[24, 156]])
expected = np.array([[0.0,0.0],[0.0,0.0]])

for i in range(0, len(row_total)):
    for j in range(0, len(column_total)):
        expected[i][j] = row_total[i]*column_total[j]/total

_chi = 0
critical_value = chi2.ppf(0.95, 1)


for i in range(0, len(expected)):
    for j in range(0, len(expected[0])):
        _chi = _chi + ((observed[j][i]-expected[j][i]) ** 2)/expected[j][i]

print(expected)
if(critical_value<_chi):
    print (f"Reject :critical: {critical_value}\tcalculated: {_chi}")
else:    
    print (f"Fail to Reject :critical: {critical_value}\tcalculated: {_chi}")



[[ 14.4 105.6]
 [ 21.6 158.4]]
Fail to Reject :critical: 3.841458820694124	calculated: 0.7575757575757577
